/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information.
         *
         *     Args:
         *         request: Current request
         *
         *     Returns:
         *         Current user information
         */
        get: operations["get_current_user_info_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Status
         * @description Check authentication status.
         *
         *     Args:
         *         request: Current request (provides Authorization header)
         *
         *     Returns:
         *         Authentication status and user info if authenticated
         */
        get: operations["get_auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log out current user.
         *
         *     Args:
         *         request: FastAPI request object
         *
         *     Returns:
         *         Success message
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/clerk-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clerk Session Exchange
         * @description Exchange Clerk session token for internal session token.
         *
         *     This allows the frontend to use Clerk for auth UI,
         *     but still use our internal session system for API calls.
         *
         *     Args:
         *         request: Request with Authorization header containing Clerk session token
         *
         *     Returns:
         *         ClerkSessionResponse with internal session_token and user info
         */
        post: operations["clerk_session_exchange_api_auth_clerk_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Models
         * @description Get list of available LLM models for paper reviews.
         *
         *     Returns models based on which API keys are configured.
         */
        get: operations["get_available_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Paper Reviews
         * @description List paper reviews for the authenticated user.
         *
         *     Returns a paginated list of review summaries including status.
         */
        get: operations["list_paper_reviews_api_paper_reviews_get"];
        put?: never;
        /**
         * Create Paper Review
         * @description Submit a paper for review.
         *
         *     Upload a PDF file to start an asynchronous review process. The endpoint
         *     returns immediately with a review ID that can be used to poll for results.
         *
         *     Requires authentication.
         */
        post: operations["create_paper_review_api_paper_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper-reviews/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Reviews
         * @description Get all pending or processing reviews for the authenticated user.
         *
         *     Use this endpoint to check if there are any reviews in progress.
         */
        get: operations["get_pending_reviews_api_paper_reviews_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper-reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper Review
         * @description Get a specific paper review by ID.
         *
         *     Only returns reviews owned by the authenticated user.
         *     Poll this endpoint to check if a review has completed.
         */
        get: operations["get_paper_review_api_paper_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paper-reviews/{review_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper Download Url
         * @description Get a temporary download URL for the reviewed paper PDF.
         *
         *     Returns a signed URL that expires after 1 hour. Only returns URLs
         *     for papers owned by the authenticated user.
         */
        get: operations["get_paper_download_url_api_paper_reviews__review_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Get basic API information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check API health status.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthStatus
         * @description Authentication status response.
         */
        AuthStatus: {
            /**
             * Authenticated
             * @description Whether the user is authenticated
             */
            authenticated: boolean;
            /** @description User information if authenticated */
            user?: components["schemas"]["AuthUser"] | null;
        };
        /**
         * AuthUser
         * @description User information returned by authentication endpoints.
         */
        AuthUser: {
            /**
             * Id
             * @description Database user ID
             */
            id: number;
            /**
             * Email
             * @description User email address
             */
            email: string;
            /**
             * Name
             * @description User display name
             */
            name: string;
        };
        /** Body_create_paper_review_api_paper_reviews_post */
        Body_create_paper_review_api_paper_reviews_post: {
            /**
             * File
             * Format: binary
             * @description PDF file to review
             */
            file: string;
            /**
             * Model
             * @description LLM model to use for review (provider:model format)
             */
            model: string;
            /**
             * Num Reviews Ensemble
             * @description Number of ensemble reviews (1-5)
             */
            num_reviews_ensemble: number;
            /**
             * Num Reflections
             * @description Number of reflection rounds (0-3)
             */
            num_reflections: number;
        };
        /**
         * ClerkSessionResponse
         * @description Response from Clerk session exchange.
         */
        ClerkSessionResponse: {
            /**
             * Session Token
             * @description Internal session token for API calls
             */
            session_token: string;
            /** @description Authenticated user information */
            user: components["schemas"]["AuthUser"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ModelInfo
         * @description Information about an available LLM model.
         */
        ModelInfo: {
            /**
             * Id
             * @description Model identifier in provider:model format
             */
            id: string;
            /**
             * Provider
             * @description LLM provider (anthropic, openai, xai)
             */
            provider: string;
            /**
             * Name
             * @description Human-readable model name
             */
            name: string;
            /**
             * Description
             * @description Brief description of the model
             */
            description: string;
        };
        /**
         * ModelsResponse
         * @description Response containing available models.
         */
        ModelsResponse: {
            /**
             * Models
             * @description List of available models
             */
            models: components["schemas"]["ModelInfo"][];
            /**
             * Default
             * @description Default model ID
             */
            default: string;
        };
        /**
         * PaperDownloadResponse
         * @description Response with a temporary download URL for the paper PDF.
         */
        PaperDownloadResponse: {
            /**
             * Download Url
             * @description Temporary signed URL to download the PDF
             */
            download_url: string;
            /**
             * Filename
             * @description Original filename of the PDF
             */
            filename: string;
        };
        /**
         * PaperReviewDetail
         * @description Paper review with computed fields for API responses.
         */
        PaperReviewDetail: {
            /** Id */
            id: number;
            /**
             * Status
             * @description Review status: pending, processing, completed, failed
             */
            status: string;
            /**
             * Error Message
             * @description Error message if status is failed
             */
            error_message?: string | null;
            /**
             * Original Filename
             * @description Original PDF filename
             */
            original_filename: string;
            /**
             * Model
             * @description Model used for review
             */
            model: string;
            /**
             * Created At
             * @description ISO timestamp of review creation
             */
            created_at: string;
            /**
             * Summary
             * @description Paper summary (null if not completed)
             */
            summary?: string | null;
            /**
             * Strengths
             * @description List of strengths (null if not completed)
             */
            strengths?: string[] | null;
            /**
             * Weaknesses
             * @description List of weaknesses (null if not completed)
             */
            weaknesses?: string[] | null;
            /** Originality */
            originality?: number | null;
            /** Quality */
            quality?: number | null;
            /** Clarity */
            clarity?: number | null;
            /** Significance */
            significance?: number | null;
            /** Questions */
            questions?: string[] | null;
            /** Limitations */
            limitations?: string[] | null;
            /** Ethical Concerns */
            ethical_concerns?: boolean | null;
            /**
             * Ethical Concerns Explanation
             * @default
             */
            ethical_concerns_explanation: string;
            /** Soundness */
            soundness?: number | null;
            /** Presentation */
            presentation?: number | null;
            /** Contribution */
            contribution?: number | null;
            /** Overall */
            overall?: number | null;
            /** Confidence */
            confidence?: number | null;
            /** Decision */
            decision?: string | null;
            /** @description Token usage (null if not completed) */
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /**
             * Progress
             * @description Review progress (0.0-1.0)
             */
            progress: number;
            /**
             * Progress Step
             * @description Current step description (empty string when completed)
             */
            progress_step: string;
        };
        /**
         * PaperReviewListResponse
         * @description Response for listing paper reviews.
         */
        PaperReviewListResponse: {
            /**
             * Reviews
             * @description List of review summaries
             */
            reviews: components["schemas"]["PaperReviewSummary"][];
            /**
             * Count
             * @description Number of reviews returned
             */
            count: number;
        };
        /**
         * PaperReviewStartedResponse
         * @description Response when a paper review is started.
         */
        PaperReviewStartedResponse: {
            /**
             * Review Id
             * @description Unique review ID
             */
            review_id: number;
            /**
             * Status
             * @description Review status (pending)
             */
            status: string;
        };
        /**
         * PaperReviewSummary
         * @description Summary of a paper review for list views.
         */
        PaperReviewSummary: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /** Overall */
            overall?: number | null;
            /** Decision */
            decision?: string | null;
            /** Original Filename */
            original_filename: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: string;
            /** Progress */
            progress: number;
            /** Progress Step */
            progress_step: string;
        };
        /**
         * PendingReviewSummary
         * @description Summary of a pending/processing review.
         */
        PendingReviewSummary: {
            /**
             * Id
             * @description Review ID
             */
            id: number;
            /**
             * Status
             * @description Review status
             */
            status: string;
            /**
             * Original Filename
             * @description Original PDF filename
             */
            original_filename: string;
            /**
             * Model
             * @description Model used for review
             */
            model: string;
            /**
             * Created At
             * @description ISO timestamp of review creation
             */
            created_at: string;
            /**
             * Progress
             * @description Review progress (0.0-1.0)
             */
            progress: number;
            /**
             * Progress Step
             * @description Current step description
             */
            progress_step: string;
        };
        /**
         * PendingReviewsResponse
         * @description Response for listing pending reviews.
         */
        PendingReviewsResponse: {
            /**
             * Reviews
             * @description List of pending reviews
             */
            reviews: components["schemas"]["PendingReviewSummary"][];
            /**
             * Count
             * @description Number of pending reviews
             */
            count: number;
        };
        /**
         * TokenUsage
         * @description Token usage summary for a paper review.
         */
        TokenUsage: {
            /**
             * Input Tokens
             * @description Total input tokens used
             */
            input_tokens: number;
            /**
             * Cached Input Tokens
             * @description Cached input tokens
             */
            cached_input_tokens: number;
            /**
             * Output Tokens
             * @description Total output tokens used
             */
            output_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_current_user_info_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
        };
    };
    get_auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    clerk_session_exchange_api_auth_clerk_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClerkSessionResponse"];
                };
            };
        };
    };
    get_available_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    list_paper_reviews_api_paper_reviews_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_paper_review_api_paper_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_paper_review_api_paper_reviews_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReviewStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_reviews_api_paper_reviews_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingReviewsResponse"];
                };
            };
        };
    };
    get_paper_review_api_paper_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperReviewDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_download_url_api_paper_reviews__review_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDownloadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
