# mypy: ignore-errors
# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-01-27T20:27:42+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class Status(StrEnum):
    running = "running"
    completed = "completed"
    failed = "failed"


class ActiveNode(BaseModel):
    execution_id: Annotated[str, Field(description="Unique execution ID", title="Execution Id")]
    stage: Annotated[str, Field(description="Stage identifier", title="Stage")]
    status: Annotated[
        Status | None, Field(description="Current execution status", title="Status")
    ] = "running"
    started_at: Annotated[
        AwareDatetime, Field(description="When execution started", title="Started At")
    ]
    completed_at: Annotated[
        AwareDatetime | None, Field(description="When execution completed", title="Completed At")
    ] = None
    exec_time: Annotated[
        float | None, Field(description="Execution time in seconds", title="Exec Time")
    ] = None
    run_type: Annotated[str | None, Field(description="Type of run", title="Run Type")] = (
        "main_execution"
    )


class ArtifactPresignedUrlResponse(BaseModel):
    url: Annotated[
        str, Field(description="Presigned S3 download URL (valid for 1 hour)", title="Url")
    ]
    expires_in: Annotated[
        int, Field(description="URL expiration time in seconds", title="Expires In")
    ]
    artifact_id: Annotated[int, Field(description="Artifact identifier", title="Artifact Id")]
    filename: Annotated[str, Field(description="Original filename", title="Filename")]


class ArtifactUploadedEvent(BaseModel):
    artifact_type: Annotated[str, Field(title="Artifact Type")]
    filename: Annotated[str, Field(title="Filename")]
    file_size: Annotated[int, Field(title="File Size")]
    file_type: Annotated[str, Field(title="File Type")]
    created_at: Annotated[str, Field(title="Created At")]


class ArtifactUploadedPayload(BaseModel):
    event: ArtifactUploadedEvent


class AuthUser(BaseModel):
    id: Annotated[int, Field(description="Database user ID", title="Id")]
    email: Annotated[str, Field(description="User email address", title="Email")]
    name: Annotated[str, Field(description="User display name", title="Name")]


class BestNodeSelectionEvent(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    node_id: Annotated[str, Field(title="Node Id")]
    reasoning: Annotated[str, Field(title="Reasoning")]


class BestNodeSelectionPayload(BaseModel):
    event: BestNodeSelectionEvent


class BodyUploadFileApiConversationsConversationIdFilesPost(BaseModel):
    file: Annotated[bytes, Field(title="File")]
    llm_model: Annotated[str, Field(title="Llm Model")]
    llm_provider: Annotated[str, Field(title="Llm Provider")]


class ChatRequest(BaseModel):
    message: Annotated[str, Field(description="User message content", title="Message")]
    llm_provider: Annotated[
        str, Field(description="LLM provider to use", min_length=1, title="Llm Provider")
    ]
    llm_model: Annotated[
        str, Field(description="LLM model to use", min_length=1, title="Llm Model")
    ]
    attachment_ids: Annotated[
        list[int] | None,
        Field(
            description="List of file attachment IDs to include with this message",
            title="Attachment Ids",
        ),
    ] = None
    skip_user_message_creation: Annotated[
        bool | None,
        Field(
            description="If True, skip creating a new user message (for auto-trigger of existing messages)",
            title="Skip User Message Creation",
        ),
    ] = False


class ChatStatus(StrEnum):
    analyzing_request = "analyzing_request"
    executing_tools = "executing_tools"
    getting_idea = "getting_idea"
    updating_idea = "updating_idea"
    generating_response = "generating_response"
    done = "done"


class ChatStreamContentEvent(BaseModel):
    type: Annotated[Literal["content"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ChatStreamDoneData(BaseModel):
    idea_updated: Annotated[bool, Field(title="Idea Updated")]
    assistant_response: Annotated[str, Field(title="Assistant Response")]


class ChatStreamDoneEvent(BaseModel):
    type: Annotated[Literal["done"], Field(title="Type")]
    data: ChatStreamDoneData


class ChatStreamErrorEvent(BaseModel):
    type: Annotated[Literal["error"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ChatStreamIdeaUpdatedEvent(BaseModel):
    type: Annotated[Literal["idea_updated"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ChatStreamStatusEvent(BaseModel):
    type: Annotated[Literal["status"], Field(title="Type")]
    data: ChatStatus


class CheckoutSessionCreateRequest(BaseModel):
    price_id: Annotated[str, Field(title="Price Id")]
    success_url: Annotated[AnyUrl, Field(title="Success Url")]
    cancel_url: Annotated[AnyUrl, Field(title="Cancel Url")]


class CheckoutSessionCreateResponse(BaseModel):
    checkout_url: Annotated[AnyUrl, Field(title="Checkout Url")]


class ChildConversationInfo(BaseModel):
    conversation_id: Annotated[
        int, Field(description="Child conversation ID", title="Conversation Id")
    ]
    title: Annotated[str, Field(description="Child conversation title", title="Title")]
    created_at: Annotated[str, Field(description="ISO timestamp when created", title="Created At")]
    status: Annotated[str, Field(description="Conversation status", title="Status")]


class CodexEventPayload(BaseModel):
    event: Annotated[dict[str, Any], Field(title="Event")]


class ConversationImportConflictItem(BaseModel):
    id: Annotated[int, Field(title="Id")]
    title: Annotated[str, Field(title="Title")]
    updated_at: Annotated[str, Field(title="Updated At")]
    url: Annotated[str, Field(title="Url")]


class ConversationImportContentEvent(BaseModel):
    type: Annotated[Literal["content"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ConversationImportErrorEvent(BaseModel):
    type: Annotated[Literal["error"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]
    code: Annotated[str | None, Field(title="Code")] = None


class ConversationImportMarkdownDeltaEvent(BaseModel):
    type: Annotated[Literal["markdown_delta"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ConversationImportModelLimitData(BaseModel):
    message: Annotated[str, Field(title="Message")]
    suggestion: Annotated[str | None, Field(title="Suggestion")] = None


class ConversationImportModelLimitEvent(BaseModel):
    type: Annotated[Literal["model_limit_conflict"], Field(title="Type")]
    data: ConversationImportModelLimitData


class ConversationImportProgressPayload(BaseModel):
    phase: Annotated[str, Field(title="Phase")]
    current: Annotated[int, Field(title="Current")]
    total: Annotated[int, Field(title="Total")]


class ConversationImportSectionUpdateEvent(BaseModel):
    type: Annotated[Literal["section_update"], Field(title="Type")]
    field: Annotated[str, Field(title="Field")]
    data: Annotated[str, Field(title="Data")]


class Data(StrEnum):
    importing = "importing"
    creating_manual_seed = "creating_manual_seed"
    summarizing = "summarizing"
    generating = "generating"


class ConversationImportStateEvent(BaseModel):
    type: Annotated[Literal["state"], Field(title="Type")]
    data: Annotated[Data, Field(title="Data")]


class ConversationListItem(BaseModel):
    id: Annotated[int, Field(title="Id")]
    url: Annotated[str, Field(title="Url")]
    title: Annotated[str, Field(title="Title")]
    import_date: Annotated[str, Field(title="Import Date")]
    created_at: Annotated[str, Field(title="Created At")]
    updated_at: Annotated[str, Field(title="Updated At")]
    user_id: Annotated[int, Field(title="User Id")]
    user_name: Annotated[str, Field(title="User Name")]
    user_email: Annotated[str, Field(title="User Email")]
    idea_title: Annotated[str | None, Field(title="Idea Title")] = None
    idea_content: Annotated[str | None, Field(title="Idea Content")] = None
    last_user_message_content: Annotated[str | None, Field(title="Last User Message Content")] = (
        None
    )
    last_assistant_message_content: Annotated[
        str | None, Field(title="Last Assistant Message Content")
    ] = None
    manual_title: Annotated[str | None, Field(title="Manual Title")] = None
    manual_hypothesis: Annotated[str | None, Field(title="Manual Hypothesis")] = None
    status: Annotated[str | None, Field(title="Status")] = "draft"


class ConversationListResponse(BaseModel):
    conversations: Annotated[
        list[ConversationListItem],
        Field(description="List of conversations", title="Conversations"),
    ]


class ConversationUpdate(BaseModel):
    title: Annotated[
        str, Field(description="New title for the conversation", min_length=1, title="Title")
    ]


class CreditPackModel(BaseModel):
    price_id: Annotated[str, Field(title="Price Id")]
    credits: Annotated[int, Field(title="Credits")]
    currency: Annotated[str, Field(title="Currency")]
    unit_amount: Annotated[int, Field(title="Unit Amount")]
    nickname: Annotated[str, Field(title="Nickname")]


class CreditTransactionModel(BaseModel):
    id: Annotated[int, Field(title="Id")]
    amount: Annotated[int, Field(title="Amount")]
    transaction_type: Annotated[str, Field(title="Transaction Type")]
    status: Annotated[str, Field(title="Status")]
    description: Annotated[str | None, Field(title="Description")] = None
    metadata: Annotated[dict[str, Any] | None, Field(title="Metadata")] = None
    stripe_session_id: Annotated[str | None, Field(title="Stripe Session Id")] = None
    created_at: Annotated[str, Field(title="Created At")]


class DatasetFileInfo(BaseModel):
    s3_key: Annotated[str, Field(title="S3 Key")]
    relative_path: Annotated[str, Field(title="Relative Path")]
    size: Annotated[int, Field(title="Size")]
    download_url: Annotated[str, Field(title="Download Url")]


class DatasetUploadUrlRequest(BaseModel):
    datasets_folder: Annotated[str, Field(title="Datasets Folder")]
    relative_path: Annotated[str, Field(title="Relative Path")]
    content_type: Annotated[str, Field(title="Content Type")]
    file_size: Annotated[int, Field(title="File Size")]


class DatasetUploadUrlResponse(BaseModel):
    upload_url: Annotated[str, Field(title="Upload Url")]
    s3_key: Annotated[str, Field(title="S3 Key")]
    expires_in: Annotated[int, Field(title="Expires In")]


class ErrorResponse(BaseModel):
    error: Annotated[str, Field(description="Error message", title="Error")]
    detail: Annotated[str | None, Field(description="Additional error details", title="Detail")] = (
        None
    )


class FigureReviewEvent(BaseModel):
    figure_name: Annotated[str, Field(title="Figure Name")]
    img_description: Annotated[str, Field(title="Img Description")]
    img_review: Annotated[str, Field(title="Img Review")]
    caption_review: Annotated[str, Field(title="Caption Review")]
    figrefs_review: Annotated[str, Field(title="Figrefs Review")]
    source_path: Annotated[str | None, Field(title="Source Path")] = None


class FigureReviewsEvent(BaseModel):
    reviews: Annotated[list[FigureReviewEvent], Field(title="Reviews")]


class FigureReviewsPayload(BaseModel):
    event: FigureReviewsEvent


class FileAttachment(BaseModel):
    id: Annotated[int, Field(description="Unique attachment ID", title="Id")]
    filename: Annotated[str, Field(description="Original filename", title="Filename")]
    file_size: Annotated[int, Field(description="File size in bytes", title="File Size")]
    file_type: Annotated[str, Field(description="MIME type of the file", title="File Type")]
    s3_key: Annotated[str, Field(description="S3 storage key", title="S3 Key")]
    created_at: Annotated[
        str, Field(description="ISO format creation timestamp", title="Created At")
    ]


class FileListResponse(BaseModel):
    files: Annotated[
        list[FileAttachment], Field(description="List of file attachments", title="Files")
    ]
    file_count: Annotated[int, Field(description="Number of files", title="File Count")]


class FileMetadata(BaseModel):
    id: Annotated[int, Field(description="File attachment ID", title="Id")]
    s3_key: Annotated[str, Field(description="S3 storage key", title="S3 Key")]
    filename: Annotated[str, Field(description="Original filename", title="Filename")]
    file_size: Annotated[int, Field(description="File size in bytes", title="File Size")]
    file_type: Annotated[str, Field(description="MIME type", title="File Type")]
    conversation_id: Annotated[
        int, Field(description="Associated conversation ID", title="Conversation Id")
    ]


class FileUploadResponse(BaseModel):
    file: Annotated[FileMetadata, Field(description="Uploaded file metadata")]
    message: Annotated[str, Field(description="Success message", title="Message")]


class GPUShortagePayload(BaseModel):
    required_gpus: Annotated[int, Field(title="Required Gpus")]
    available_gpus: Annotated[int, Field(title="Available Gpus")]
    message: Annotated[str | None, Field(title="Message")] = None


class GpuTypeListResponse(BaseModel):
    gpu_types: Annotated[list[str], Field(title="Gpu Types")]
    gpu_prices: Annotated[dict[str, float | None], Field(title="Gpu Prices")]


class HardwareStatsPartition(BaseModel):
    partition: Annotated[str, Field(title="Partition")]
    used_bytes: Annotated[int, Field(title="Used Bytes")]


class HardwareStatsPayload(BaseModel):
    partitions: Annotated[list[HardwareStatsPartition] | None, Field(title="Partitions")] = None


class IdeaRefinementRequest(BaseModel):
    title: Annotated[str, Field(description="Title of the research idea", title="Title")]
    idea_markdown: Annotated[
        str, Field(description="Research idea in markdown format", title="Idea Markdown")
    ]


class IdeaVersion(BaseModel):
    version_id: Annotated[int, Field(description="Version ID", title="Version Id")]
    title: Annotated[str, Field(description="Title of the research idea", title="Title")]
    idea_markdown: Annotated[
        str, Field(description="Research idea in markdown format", title="Idea Markdown")
    ]
    is_manual_edit: Annotated[
        bool,
        Field(
            description="Whether this version was manually edited by user", title="Is Manual Edit"
        ),
    ]
    version_number: Annotated[
        int, Field(description="Version number for ordering", title="Version Number")
    ]
    created_at: Annotated[
        str, Field(description="ISO format creation timestamp", title="Created At")
    ]


class IdeaVersionsResponse(BaseModel):
    versions: Annotated[
        list[IdeaVersion], Field(description="List of idea versions", title="Versions")
    ]


class ImportChatCreateNew(BaseModel):
    url: Annotated[
        str, Field(description="Share URL to import (ChatGPT or BranchPrompt)", title="Url")
    ]
    llm_model: Annotated[
        str, Field(description="LLM model to use", min_length=1, title="Llm Model")
    ]
    llm_provider: Annotated[
        str, Field(description="LLM provider to use", min_length=1, title="Llm Provider")
    ]
    duplicate_resolution: Annotated[Literal["create_new"], Field(title="Duplicate Resolution")]


class ImportChatPrompt(BaseModel):
    url: Annotated[
        str, Field(description="Share URL to import (ChatGPT or BranchPrompt)", title="Url")
    ]
    llm_model: Annotated[
        str, Field(description="LLM model to use", min_length=1, title="Llm Model")
    ]
    llm_provider: Annotated[
        str, Field(description="LLM provider to use", min_length=1, title="Llm Provider")
    ]
    duplicate_resolution: Annotated[Literal["prompt"], Field(title="Duplicate Resolution")]


class ImportChatUpdateExisting(BaseModel):
    url: Annotated[
        str, Field(description="Share URL to import (ChatGPT or BranchPrompt)", title="Url")
    ]
    llm_model: Annotated[
        str, Field(description="LLM model to use", min_length=1, title="Llm Model")
    ]
    llm_provider: Annotated[
        str, Field(description="LLM provider to use", min_length=1, title="Llm Provider")
    ]
    duplicate_resolution: Annotated[Literal["update_existing"], Field(title="Duplicate Resolution")]
    target_conversation_id: Annotated[
        int,
        Field(
            description="Conversation ID to update when duplicate_resolution is update_existing",
            title="Target Conversation Id",
        ),
    ]


class ImportedChatMessage(BaseModel):
    role: Annotated[str, Field(description="Message role: 'user' or 'assistant'", title="Role")]
    content: Annotated[str, Field(description="Message content as Markdown", title="Content")]


class ImportedConversationSummaryUpdate(BaseModel):
    summary: Annotated[
        str, Field(description="Updated summary text", min_length=1, title="Summary")
    ]


class InitializationProgressPayload(BaseModel):
    message: Annotated[str, Field(title="Message")]


class LLMDefault(BaseModel):
    llm_provider: Annotated[
        str, Field(description="LLM provider name", min_length=1, title="Llm Provider")
    ]
    llm_model: Annotated[str, Field(description="LLM model name", min_length=1, title="Llm Model")]


class LLMDefaultsResponse(BaseModel):
    current_default: Annotated[LLMDefault, Field(description="Current default LLM settings")]


class LLMDefaultsUpdateRequest(BaseModel):
    llm_provider: Annotated[
        str, Field(description="LLM provider name", min_length=1, title="Llm Provider")
    ]
    llm_model: Annotated[str, Field(description="LLM model name", min_length=1, title="Llm Model")]


class LLMDefaultsUpdateResponse(BaseModel):
    message: Annotated[str, Field(description="Success message", title="Message")]
    updated_default: Annotated[LLMDefault, Field(description="The updated default settings")]


class LLMModel(BaseModel):
    id: Annotated[str, Field(description="Model ID", title="Id")]
    provider: Annotated[str, Field(description="LLM provider name", title="Provider")]
    label: Annotated[str, Field(description="Human-readable model label", title="Label")]
    supports_images: Annotated[
        bool, Field(description="Whether the model supports images", title="Supports Images")
    ]
    supports_pdfs: Annotated[
        bool, Field(description="Whether the model supports PDFs", title="Supports Pdfs")
    ]
    context_window_tokens: Annotated[
        int,
        Field(
            description="Approximate maximum context window size in tokens",
            title="Context Window Tokens",
        ),
    ]


class LLMPromptCreateRequest(BaseModel):
    prompt_type: Annotated[
        str, Field(description="Type of prompt", min_length=1, title="Prompt Type")
    ]
    system_prompt: Annotated[
        str, Field(description="The system prompt text", min_length=1, title="System Prompt")
    ]


class LLMPromptDeleteResponse(BaseModel):
    message: Annotated[str, Field(description="Success or error message", title="Message")]


class LLMPromptResponse(BaseModel):
    system_prompt: Annotated[
        str, Field(description="The system prompt text", title="System Prompt")
    ]
    is_default: Annotated[
        bool,
        Field(description="Whether this is using the default prompt from code", title="Is Default"),
    ]


class LLMProvidersResponse(BaseModel):
    providers: Annotated[
        dict[str, list[LLMModel]],
        Field(description="Available providers and their models", title="Providers"),
    ]


class LaunchResearchRunRequest(BaseModel):
    gpu_type: Annotated[str, Field(title="Gpu Type")]


class ListDatasetsRequest(BaseModel):
    datasets_folder: Annotated[str, Field(title="Datasets Folder")]


class ListDatasetsResponse(BaseModel):
    files: Annotated[list[DatasetFileInfo], Field(title="Files")]
    expires_in: Annotated[int, Field(title="Expires In")]


class LlmReviewNotFoundResponse(BaseModel):
    run_id: Annotated[str, Field(description="Research run identifier", title="Run Id")]
    exists: Annotated[
        bool | None, Field(description="Indicates no review exists", title="Exists")
    ] = False
    message: Annotated[
        str, Field(description="Explanation that no review was found", title="Message")
    ]


class LlmReviewResponse(BaseModel):
    id: Annotated[int, Field(description="Unique identifier of the review", title="Id")]
    run_id: Annotated[str, Field(description="Research run identifier", title="Run Id")]
    summary: Annotated[str, Field(description="Executive summary of the review", title="Summary")]
    strengths: Annotated[
        list[str], Field(description="List of identified strengths", title="Strengths")
    ]
    weaknesses: Annotated[
        list[str], Field(description="List of identified weaknesses", title="Weaknesses")
    ]
    originality: Annotated[float, Field(description="Originality score (1-4)", title="Originality")]
    quality: Annotated[float, Field(description="Quality score (1-4)", title="Quality")]
    clarity: Annotated[float, Field(description="Clarity score (1-4)", title="Clarity")]
    significance: Annotated[
        float, Field(description="Significance score (1-4)", title="Significance")
    ]
    questions: Annotated[
        list[str], Field(description="List of reviewer questions", title="Questions")
    ]
    limitations: Annotated[
        list[str], Field(description="List of identified limitations", title="Limitations")
    ]
    ethical_concerns: Annotated[
        bool, Field(description="Whether ethical concerns were raised", title="Ethical Concerns")
    ]
    soundness: Annotated[float, Field(description="Soundness score (1-4)", title="Soundness")]
    presentation: Annotated[
        float, Field(description="Presentation score (1-4)", title="Presentation")
    ]
    contribution: Annotated[
        float, Field(description="Contribution score (1-4)", title="Contribution")
    ]
    overall: Annotated[float, Field(description="Overall quality score (1-10)", title="Overall")]
    confidence: Annotated[
        float, Field(description="Reviewer confidence score (1-5)", title="Confidence")
    ]
    decision: Annotated[
        str, Field(description="Final decision ('Accept' or 'Reject')", title="Decision")
    ]
    source_path: Annotated[
        str | None,
        Field(description="Source path or reference for the review", title="Source Path"),
    ] = None
    created_at: Annotated[
        str, Field(description="ISO timestamp when the review was created", title="Created At")
    ]


class ManualIdeaSeedRequest(BaseModel):
    idea_title: Annotated[
        str, Field(description="Idea title to seed generation", min_length=1, title="Idea Title")
    ]
    idea_hypothesis: Annotated[
        str,
        Field(
            description="Idea hypothesis to seed generation", min_length=1, title="Idea Hypothesis"
        ),
    ]
    llm_provider: Annotated[
        str, Field(description="LLM provider identifier", min_length=1, title="Llm Provider")
    ]
    llm_model: Annotated[
        str, Field(description="LLM model identifier", min_length=1, title="Llm Model")
    ]


class MessageResponse(BaseModel):
    message: Annotated[str, Field(description="Response message", title="Message")]


class MetricInterpretation(BaseModel):
    name: Annotated[
        str, Field(description="Metric name", examples=["accuracy", "f1_score"], title="Name")
    ]
    value: Annotated[float, Field(description="Raw metric value", title="Value")]
    formatted: Annotated[
        str,
        Field(description="Formatted for display", examples=["82.3%", "0.823"], title="Formatted"),
    ]
    interpretation: Annotated[
        str | None,
        Field(
            description="What this value means",
            examples=["5.2% above baseline", "Best result so far"],
            title="Interpretation",
        ),
    ] = None
    context: Annotated[
        str | None,
        Field(
            description="Evaluation context",
            examples=["Validation set", "Test dataset"],
            title="Context",
        ),
    ] = None
    comparison: Annotated[
        dict[str, Any] | None,
        Field(
            description="Comparison with baseline/previous best",
            examples=[
                {
                    "baseline": 0.77,
                    "delta_vs_baseline": 0.053,
                    "delta_vs_previous": 0.013,
                    "previous_best": 0.81,
                }
            ],
            title="Comparison",
        ),
    ] = None


class ModelCost(BaseModel):
    model: Annotated[str, Field(title="Model")]
    cost: Annotated[float, Field(title="Cost")]


class Status1(StrEnum):
    success = "success"
    failed = "failed"


class NodeExecutionCompletedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["node_execution_completed"], Field(title="Type")] = (
        "node_execution_completed"
    )
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    execution_id: Annotated[str, Field(description="Unique execution ID", title="Execution Id")]
    status: Annotated[Status1, Field(description="Execution status", title="Status")]
    exec_time: Annotated[float, Field(description="Execution time in seconds", title="Exec Time")]
    run_type: Annotated[str | None, Field(description="Type of run", title="Run Type")] = (
        "main_execution"
    )


class NodeExecutionStartedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["node_execution_started"], Field(title="Type")] = (
        "node_execution_started"
    )
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    execution_id: Annotated[str, Field(description="Unique execution ID", title="Execution Id")]
    run_type: Annotated[str | None, Field(description="Type of run", title="Run Type")] = (
        "main_execution"
    )
    code_preview: Annotated[
        str | None, Field(description="Preview of code being executed", title="Code Preview")
    ] = None


class Outcome(StrEnum):
    success = "success"
    failure = "failure"
    partial = "partial"


class PaperGenerationProgressEvent(BaseModel):
    step: Annotated[str, Field(title="Step")]
    substep: Annotated[str | None, Field(title="Substep")] = None
    progress: Annotated[float, Field(title="Progress")]
    step_progress: Annotated[float, Field(title="Step Progress")]
    details: Annotated[dict[str, Any] | None, Field(title="Details")] = None


class PaperGenerationProgressPayload(BaseModel):
    event: PaperGenerationProgressEvent


class Step(StrEnum):
    plot_aggregation = "plot_aggregation"
    citation_gathering = "citation_gathering"
    paper_writeup = "paper_writeup"
    paper_review = "paper_review"


class PaperGenerationStepEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["paper_generation_step"], Field(title="Type")] = "paper_generation_step"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    step: Annotated[Step, Field(description="Current step", title="Step")]
    substep: Annotated[str | None, Field(description="Substep if applicable", title="Substep")] = (
        None
    )
    description: Annotated[
        str | None, Field(description="What's happening in this step", title="Description")
    ] = None
    progress: Annotated[float, Field(description="Overall progress (0.0-1.0)", title="Progress")]
    step_progress: Annotated[
        float, Field(description="Progress within this step (0.0-1.0)", title="Step Progress")
    ]
    details: Annotated[
        dict[str, Any] | None,
        Field(
            description="Step-specific details (figures selected, citations found, etc.)",
            title="Details",
        ),
    ] = None


class ParentRunFileInfo(BaseModel):
    s3_key: Annotated[str, Field(title="S3 Key")]
    filename: Annotated[str, Field(title="Filename")]
    size: Annotated[int, Field(title="Size")]
    download_url: Annotated[str, Field(title="Download Url")]


class ParentRunFilesRequest(BaseModel):
    parent_run_id: Annotated[str, Field(title="Parent Run Id")]


class ParentRunFilesResponse(BaseModel):
    files: Annotated[list[ParentRunFileInfo], Field(title="Files")]
    expires_in: Annotated[int, Field(title="Expires In")]


class PresignedUploadUrlRequest(BaseModel):
    artifact_type: Annotated[str, Field(title="Artifact Type")]
    filename: Annotated[str, Field(title="Filename")]
    content_type: Annotated[str, Field(title="Content Type")]
    file_size: Annotated[int, Field(title="File Size")]
    metadata: Annotated[dict[str, str] | None, Field(title="Metadata")] = None


class PresignedUploadUrlResponse(BaseModel):
    upload_url: Annotated[str, Field(title="Upload Url")]
    s3_key: Annotated[str, Field(title="S3 Key")]
    expires_in: Annotated[int, Field(title="Expires In")]


class ResearchCost(BaseModel):
    run_id: Annotated[str, Field(title="Run Id")]
    cost: Annotated[float, Field(title="Cost")]


class ResearchRunAcceptedResponse(BaseModel):
    status: Annotated[str | None, Field(title="Status")] = "ok"
    run_id: Annotated[str, Field(title="Run Id")]
    pod_id: Annotated[str, Field(title="Pod Id")]
    pod_name: Annotated[str, Field(title="Pod Name")]
    gpu_type: Annotated[str, Field(title="Gpu Type")]
    cost: Annotated[float, Field(title="Cost")]


class ResearchRunArtifactMetadata(BaseModel):
    id: Annotated[int, Field(description="Artifact identifier", title="Id")]
    artifact_type: Annotated[str, Field(description="Artifact type label", title="Artifact Type")]
    filename: Annotated[str, Field(description="Original filename", title="Filename")]
    file_size: Annotated[int, Field(description="File size in bytes", title="File Size")]
    file_type: Annotated[str, Field(description="MIME type", title="File Type")]
    created_at: Annotated[
        str, Field(description="ISO timestamp when the artifact was recorded", title="Created At")
    ]
    run_id: Annotated[str, Field(description="Research run identifier", title="Run Id")]
    conversation_id: Annotated[
        int | None, Field(description="ID of the associated conversation", title="Conversation Id")
    ] = None


class ResearchRunBestNodeSelection(BaseModel):
    id: Annotated[int, Field(description="Unique identifier of the reasoning record", title="Id")]
    stage: Annotated[
        str, Field(description="Stage identifier where the selection happened", title="Stage")
    ]
    node_id: Annotated[str, Field(description="Identifier of the selected node", title="Node Id")]
    reasoning: Annotated[
        str, Field(description="LLM reasoning that justified the selection", title="Reasoning")
    ]
    created_at: Annotated[
        str, Field(description="ISO timestamp when the reasoning was recorded", title="Created At")
    ]


class Status3(StrEnum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class ResearchRunCompleteData(BaseModel):
    status: Annotated[Status3, Field(title="Status")]
    success: Annotated[bool | None, Field(title="Success")] = None
    message: Annotated[str | None, Field(title="Message")] = None


class ResearchRunCompleteEvent(BaseModel):
    type: Annotated[Literal["complete"], Field(title="Type")]
    data: ResearchRunCompleteData


class ResearchRunCostResponse(BaseModel):
    total_cost: Annotated[float, Field(title="Total Cost")]
    cost_by_model: Annotated[list[ModelCost], Field(title="Cost By Model")]


class ResearchRunErrorEvent(BaseModel):
    type: Annotated[Literal["error"], Field(title="Type")]
    data: Annotated[str, Field(title="Data")]


class ResearchRunEvent(BaseModel):
    id: Annotated[int, Field(description="Unique identifier of the audit event", title="Id")]
    run_id: Annotated[
        str, Field(description="Run identifier that produced the event", title="Run Id")
    ]
    event_type: Annotated[str, Field(description="Audit event type label", title="Event Type")]
    metadata: Annotated[
        dict[str, Any] | None,
        Field(description="Structured metadata captured for the event", title="Metadata"),
    ] = None
    occurred_at: Annotated[
        str, Field(description="ISO timestamp when the event was recorded", title="Occurred At")
    ]


class ResearchRunHeartbeatEvent(BaseModel):
    type: Annotated[Literal["heartbeat"], Field(title="Type")]
    data: Annotated[dict[str, Any] | None, Field(title="Data")] = None


class ResearchRunHwCostActualData(BaseModel):
    hw_actual_cost_cents: Annotated[
        int,
        Field(
            description="Actual hardware cost in cents as billed by RunPod.",
            title="Hw Actual Cost Cents",
        ),
    ]
    hw_actual_cost_updated_at: Annotated[
        str,
        Field(
            description="ISO timestamp when the billing summary was recorded.",
            title="Hw Actual Cost Updated At",
        ),
    ]
    billing_summary: Annotated[
        dict[str, Any] | None,
        Field(
            description="Raw billing summary metadata returned by RunPod.", title="Billing Summary"
        ),
    ] = None


class ResearchRunHwCostActualEvent(BaseModel):
    type: Annotated[Literal["hw_cost_actual"], Field(title="Type")]
    data: ResearchRunHwCostActualData


class ResearchRunHwCostEstimateData(BaseModel):
    hw_estimated_cost_cents: Annotated[
        int,
        Field(
            description="Estimated hardware cost in cents since the run started running.",
            title="Hw Estimated Cost Cents",
        ),
    ]
    hw_cost_per_hour_cents: Annotated[
        int,
        Field(
            description="RunPod hourly cost in cents recorded at launch.",
            title="Hw Cost Per Hour Cents",
        ),
    ]
    hw_started_running_at: Annotated[
        str | None,
        Field(
            description="ISO timestamp when the run transitioned from pending to running.",
            title="Hw Started Running At",
        ),
    ] = None


class ResearchRunHwCostEstimateEvent(BaseModel):
    type: Annotated[Literal["hw_cost_estimate"], Field(title="Type")]
    data: ResearchRunHwCostEstimateData


class TerminationStatus(StrEnum):
    none = "none"
    requested = "requested"
    in_progress = "in_progress"
    terminated = "terminated"
    failed = "failed"


class ResearchRunInfo(BaseModel):
    run_id: Annotated[str, Field(description="Unique identifier of the run", title="Run Id")]
    status: Annotated[str, Field(description="Current status of the run", title="Status")]
    idea_id: Annotated[int, Field(description="Idea ID associated with the run", title="Idea Id")]
    idea_version_id: Annotated[
        int, Field(description="Idea version ID associated with the run", title="Idea Version Id")
    ]
    pod_id: Annotated[
        str | None, Field(description="RunPod identifier, when available", title="Pod Id")
    ] = None
    pod_name: Annotated[
        str | None, Field(description="Human-friendly pod name", title="Pod Name")
    ] = None
    gpu_type: Annotated[str | None, Field(description="Requested GPU type", title="Gpu Type")] = (
        None
    )
    cost: Annotated[
        float,
        Field(description="Hourly RunPod cost (USD) captured when the run launched", title="Cost"),
    ]
    public_ip: Annotated[
        str | None, Field(description="Pod public IP address", title="Public Ip")
    ] = None
    ssh_port: Annotated[str | None, Field(description="Pod SSH port mapping", title="Ssh Port")] = (
        None
    )
    pod_host_id: Annotated[
        str | None, Field(description="RunPod host identifier", title="Pod Host Id")
    ] = None
    error_message: Annotated[
        str | None, Field(description="Failure details, if any", title="Error Message")
    ] = None
    last_heartbeat_at: Annotated[
        str | None,
        Field(description="ISO timestamp of the most recent heartbeat", title="Last Heartbeat At"),
    ] = None
    heartbeat_failures: Annotated[
        int | None, Field(description="Consecutive missed heartbeats", title="Heartbeat Failures")
    ] = 0
    created_at: Annotated[
        str, Field(description="ISO timestamp when the run was created", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO timestamp when the run was last updated", title="Updated At")
    ]
    initialization_status: Annotated[
        str,
        Field(
            description="Initialization status message (pending/initializing/running)",
            title="Initialization Status",
        ),
    ]
    start_deadline_at: Annotated[
        str | None,
        Field(
            description="ISO timestamp representing the start deadline window",
            title="Start Deadline At",
        ),
    ] = None
    termination_status: Annotated[
        TerminationStatus,
        Field(
            description="Termination workflow status for the associated pod cleanup.",
            title="Termination Status",
        ),
    ]
    termination_last_error: Annotated[
        str | None,
        Field(
            description="Last termination workflow error, if any.", title="Termination Last Error"
        ),
    ] = None
    parent_run_id: Annotated[
        str | None,
        Field(
            description="Parent run ID if this run's conversation was seeded from a previous run",
            title="Parent Run Id",
        ),
    ] = None


class ResearchRunInitializationStatusData(BaseModel):
    initialization_status: Annotated[
        str,
        Field(
            description="Latest initialization status message for the run.",
            title="Initialization Status",
        ),
    ]
    updated_at: Annotated[
        str, Field(description="ISO timestamp for the status update.", title="Updated At")
    ]


class ResearchRunInitializationStatusEvent(BaseModel):
    type: Annotated[Literal["initialization_status"], Field(title="Type")]
    data: ResearchRunInitializationStatusData


class ResearchRunListItem(BaseModel):
    run_id: Annotated[str, Field(description="Unique identifier of the run", title="Run Id")]
    status: Annotated[str, Field(description="Current status of the run", title="Status")]
    initialization_status: Annotated[
        str,
        Field(
            description="Initialization status message (pending/initializing/running)",
            title="Initialization Status",
        ),
    ]
    idea_title: Annotated[str, Field(description="Title from the idea version", title="Idea Title")]
    idea_hypothesis: Annotated[
        str | None,
        Field(description="Short hypothesis from the idea version", title="Idea Hypothesis"),
    ] = None
    current_stage: Annotated[
        str | None, Field(description="Latest stage from progress events", title="Current Stage")
    ] = None
    progress: Annotated[
        float | None,
        Field(
            description="Overall pipeline progress (0-1) computed as completed-stages-only buckets (0.0, 0.2, 0.4, 0.6, 0.8, 1.0).",
            title="Progress",
        ),
    ] = None
    gpu_type: Annotated[
        str | None, Field(description="GPU type used for the run", title="Gpu Type")
    ] = None
    cost: Annotated[
        float,
        Field(description="Hourly RunPod cost (USD) captured when the pod launched", title="Cost"),
    ]
    best_metric: Annotated[
        str | None, Field(description="Best metric from latest progress event", title="Best Metric")
    ] = None
    created_by_name: Annotated[
        str, Field(description="Name of the user who created the run", title="Created By Name")
    ]
    created_at: Annotated[
        str, Field(description="ISO timestamp when the run was created", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO timestamp when the run was last updated", title="Updated At")
    ]
    artifacts_count: Annotated[
        int | None,
        Field(description="Number of artifacts produced by this run", title="Artifacts Count"),
    ] = 0
    error_message: Annotated[
        str | None, Field(description="Error message if the run failed", title="Error Message")
    ] = None
    conversation_id: Annotated[
        int, Field(description="ID of the associated conversation", title="Conversation Id")
    ]
    parent_run_id: Annotated[
        str | None,
        Field(
            description="Parent run ID if this run's conversation was seeded from a previous run",
            title="Parent Run Id",
        ),
    ] = None


class ResearchRunListResponse(BaseModel):
    items: Annotated[
        list[ResearchRunListItem] | None, Field(description="List of research runs", title="Items")
    ] = None
    total: Annotated[int, Field(description="Total count of research runs", title="Total")]


class ResearchRunLogEntry(BaseModel):
    id: Annotated[int, Field(description="Unique identifier of the log event", title="Id")]
    level: Annotated[str, Field(description="Log level (info, warn, error, ...)", title="Level")]
    message: Annotated[str, Field(description="Log message", title="Message")]
    created_at: Annotated[
        str, Field(description="ISO timestamp of the log event", title="Created At")
    ]


class ResearchRunLogEvent(BaseModel):
    type: Annotated[Literal["log"], Field(title="Type")]
    data: ResearchRunLogEntry


class ResearchRunPaperGenerationProgress(BaseModel):
    id: Annotated[
        int, Field(description="Unique identifier of the paper generation event", title="Id")
    ]
    run_id: Annotated[str, Field(description="Research run identifier", title="Run Id")]
    step: Annotated[
        str,
        Field(
            description="Current step: plot_aggregation, citation_gathering, paper_writeup, or paper_review",
            title="Step",
        ),
    ]
    substep: Annotated[
        str | None,
        Field(description="Substep identifier (e.g., 'round_1', 'revision_2')", title="Substep"),
    ] = None
    progress: Annotated[float, Field(description="Overall progress (0.0-1.0)", title="Progress")]
    step_progress: Annotated[
        float, Field(description="Progress within current step (0.0-1.0)", title="Step Progress")
    ]
    details: Annotated[
        dict[str, Any] | None,
        Field(
            description="Step-specific metadata (figures, citations, scores, etc.)", title="Details"
        ),
    ] = None
    created_at: Annotated[
        str, Field(description="ISO timestamp when the event was recorded", title="Created At")
    ]


class ResearchRunReviewCompletedEvent(BaseModel):
    type: Annotated[Literal["review_completed"], Field(title="Type")]
    data: LlmReviewResponse


class ResearchRunRunEvent(BaseModel):
    type: Annotated[Literal["run_event"], Field(title="Type")]
    data: ResearchRunEvent


class ResearchRunStageProgress(BaseModel):
    stage: Annotated[str, Field(description="Stage identifier", title="Stage")]
    iteration: Annotated[int, Field(description="Current iteration number", title="Iteration")]
    max_iterations: Annotated[
        int, Field(description="Maximum iterations for the stage", title="Max Iterations")
    ]
    progress: Annotated[float, Field(description="Progress percentage (0-1)", title="Progress")]
    total_nodes: Annotated[
        int, Field(description="Total nodes considered so far", title="Total Nodes")
    ]
    buggy_nodes: Annotated[int, Field(description="Number of buggy nodes", title="Buggy Nodes")]
    good_nodes: Annotated[int, Field(description="Number of good nodes", title="Good Nodes")]
    best_metric: Annotated[
        str | None, Field(description="Best metric reported at this stage", title="Best Metric")
    ] = None
    eta_s: Annotated[
        int | None, Field(description="Estimated time remaining in seconds", title="Eta S")
    ] = None
    latest_iteration_time_s: Annotated[
        int | None,
        Field(
            description="Duration of the latest iteration in seconds",
            title="Latest Iteration Time S",
        ),
    ] = None
    created_at: Annotated[
        str, Field(description="ISO timestamp when the event was recorded", title="Created At")
    ]


class ResearchRunStageProgressEvent(BaseModel):
    type: Annotated[Literal["stage_progress"], Field(title="Type")]
    data: ResearchRunStageProgress


class ResearchRunStageSkipWindow(BaseModel):
    id: Annotated[
        int, Field(description="Unique identifier for the skip window record", title="Id")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier where skipping became possible", title="Stage")
    ]
    opened_at: Annotated[
        str, Field(description="ISO timestamp when the window opened", title="Opened At")
    ]
    opened_reason: Annotated[
        str | None,
        Field(description="Reason provided when the window opened", title="Opened Reason"),
    ] = None
    closed_at: Annotated[
        str | None,
        Field(description="ISO timestamp when the window closed (if closed)", title="Closed At"),
    ] = None
    closed_reason: Annotated[
        str | None,
        Field(description="Reason provided when the window closed", title="Closed Reason"),
    ] = None


class State(StrEnum):
    opened = "opened"
    closed = "closed"


class ResearchRunStageSkipWindowUpdate(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    state: Annotated[State, Field(title="State")]
    timestamp: Annotated[str, Field(title="Timestamp")]
    reason: Annotated[str | None, Field(title="Reason")] = None


class ResearchRunStopResponse(BaseModel):
    run_id: Annotated[str, Field(title="Run Id")]
    status: Annotated[str, Field(title="Status")]
    message: Annotated[str, Field(title="Message")]


class ResearchRunSubstageEvent(BaseModel):
    id: Annotated[
        int, Field(description="Unique identifier of the sub-stage completion event", title="Id")
    ]
    stage: Annotated[str, Field(description="Stage identifier", title="Stage")]
    node_id: Annotated[
        str | None,
        Field(
            description="Optional identifier associated with the sub-stage (reserved for future use)",
            title="Node Id",
        ),
    ] = None
    summary: Annotated[
        dict[str, Any],
        Field(description="Summary payload stored for this sub-stage", title="Summary"),
    ]
    created_at: Annotated[str, Field(description="ISO timestamp of the event", title="Created At")]


class ResearchRunSubstageEventStream(BaseModel):
    type: Annotated[Literal["substage_event"], Field(title="Type")]
    data: ResearchRunSubstageEvent


class ResearchRunSubstageSummary(BaseModel):
    id: Annotated[
        int, Field(description="Unique identifier of the sub-stage summary event", title="Id")
    ]
    stage: Annotated[str, Field(description="Stage identifier", title="Stage")]
    summary: Annotated[
        dict[str, Any], Field(description="LLM-generated summary payload", title="Summary")
    ]
    created_at: Annotated[
        str, Field(description="ISO timestamp when the summary was recorded", title="Created At")
    ]


class ResearchRunSubstageSummaryEvent(BaseModel):
    type: Annotated[Literal["substage_summary"], Field(title="Type")]
    data: ResearchRunSubstageSummary


class ResearchRunSummary(BaseModel):
    run_id: Annotated[str, Field(description="Unique identifier of the run", title="Run Id")]
    status: Annotated[str, Field(description="Current status of the run", title="Status")]
    idea_id: Annotated[int, Field(description="Idea ID associated with the run", title="Idea Id")]
    idea_version_id: Annotated[
        int, Field(description="Idea version ID associated with the run", title="Idea Version Id")
    ]
    pod_id: Annotated[
        str | None, Field(description="RunPod identifier, when available", title="Pod Id")
    ] = None
    pod_name: Annotated[
        str | None, Field(description="Human-friendly pod name", title="Pod Name")
    ] = None
    gpu_type: Annotated[str | None, Field(description="Requested GPU type", title="Gpu Type")] = (
        None
    )
    cost: Annotated[
        float,
        Field(description="Hourly RunPod cost (USD) captured when the run launched", title="Cost"),
    ]
    public_ip: Annotated[
        str | None, Field(description="Pod public IP address", title="Public Ip")
    ] = None
    ssh_port: Annotated[str | None, Field(description="Pod SSH port mapping", title="Ssh Port")] = (
        None
    )
    pod_host_id: Annotated[
        str | None, Field(description="RunPod host identifier", title="Pod Host Id")
    ] = None
    error_message: Annotated[
        str | None, Field(description="Failure details, if any", title="Error Message")
    ] = None
    last_heartbeat_at: Annotated[
        str | None,
        Field(description="ISO timestamp of the most recent heartbeat", title="Last Heartbeat At"),
    ] = None
    heartbeat_failures: Annotated[
        int | None, Field(description="Consecutive missed heartbeats", title="Heartbeat Failures")
    ] = 0
    created_at: Annotated[
        str, Field(description="ISO timestamp when the run was created", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO timestamp when the run was last updated", title="Updated At")
    ]


class Status5(StrEnum):
    none = "none"
    requested = "requested"
    in_progress = "in_progress"
    terminated = "terminated"
    failed = "failed"


class ResearchRunTerminationStatusData(BaseModel):
    status: Annotated[Status5, Field(title="Status")]
    last_error: Annotated[str | None, Field(title="Last Error")] = None


class ResearchRunTerminationStatusEvent(BaseModel):
    type: Annotated[Literal["termination_status"], Field(title="Type")]
    data: ResearchRunTerminationStatusData


class ReviewCompletedEvent(BaseModel):
    summary: Annotated[str, Field(title="Summary")]
    strengths: Annotated[list[str], Field(title="Strengths")]
    weaknesses: Annotated[list[str], Field(title="Weaknesses")]
    originality: Annotated[float, Field(title="Originality")]
    quality: Annotated[float, Field(title="Quality")]
    clarity: Annotated[float, Field(title="Clarity")]
    significance: Annotated[float, Field(title="Significance")]
    questions: Annotated[list[str], Field(title="Questions")]
    limitations: Annotated[list[str], Field(title="Limitations")]
    ethical_concerns: Annotated[bool, Field(title="Ethical Concerns")]
    soundness: Annotated[float, Field(title="Soundness")]
    presentation: Annotated[float, Field(title="Presentation")]
    contribution: Annotated[float, Field(title="Contribution")]
    overall: Annotated[float, Field(title="Overall")]
    confidence: Annotated[float, Field(title="Confidence")]
    decision: Annotated[str, Field(title="Decision")]
    source_path: Annotated[str | None, Field(title="Source Path")]
    created_at: Annotated[str, Field(title="Created At")]


class ReviewCompletedPayload(BaseModel):
    event: ReviewCompletedEvent


class Status6(StrEnum):
    success = "success"
    failed = "failed"


class Status7(StrEnum):
    completed = "completed"
    failed = "failed"
    cancelled = "cancelled"


class Reason(StrEnum):
    pipeline_completed = "pipeline_completed"
    pipeline_error = "pipeline_error"
    heartbeat_timeout = "heartbeat_timeout"
    deadline_exceeded = "deadline_exceeded"
    user_cancelled = "user_cancelled"
    container_died = "container_died"


class RunFinishedPayload(BaseModel):
    success: Annotated[bool, Field(title="Success")]
    message: Annotated[str | None, Field(title="Message")] = None


class RunLogEvent(BaseModel):
    message: Annotated[str, Field(title="Message")]
    level: Annotated[str | None, Field(title="Level")] = "info"


class RunLogPayload(BaseModel):
    event: RunLogEvent


class RunStartedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["run_started"], Field(title="Type")] = "run_started"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    gpu_type: Annotated[str | None, Field(description="GPU type allocated", title="Gpu Type")] = (
        None
    )
    cost_per_hour_cents: Annotated[
        int | None, Field(description="Cost per hour in cents", title="Cost Per Hour Cents")
    ] = None


class RunType(StrEnum):
    codex_execution = "codex_execution"
    runfile_execution = "runfile_execution"


class RunningCodeEventPayload(BaseModel):
    execution_id: Annotated[str, Field(title="Execution Id")]
    stage_name: Annotated[str, Field(title="Stage Name")]
    code: Annotated[str, Field(title="Code")]
    started_at: Annotated[str, Field(title="Started At")]
    run_type: RunType


class RunningCodePayload(BaseModel):
    event: RunningCodeEventPayload


class SeedFromRunResponse(BaseModel):
    conversation_id: Annotated[
        int, Field(description="ID of the new conversation", title="Conversation Id")
    ]
    idea_id: Annotated[int, Field(description="ID of the new idea", title="Idea Id")]
    message: Annotated[str, Field(description="Success message", title="Message")]


class SkipStageRequest(BaseModel):
    stage: Annotated[str | None, Field(title="Stage")] = None
    reason: Annotated[str | None, Field(title="Reason")] = None


class SkipStageResponse(BaseModel):
    status: Annotated[Literal["pending"], Field(title="Status")]
    message: Annotated[str, Field(title="Message")]


class Confidence(StrEnum):
    high = "high"
    medium = "medium"
    low = "low"


class Status8(StrEnum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"
    skipped = "skipped"


class StageGoal(BaseModel):
    stage: Annotated[str, Field(description="Stage identifier", title="Stage")]
    title: Annotated[str, Field(description="Display title", title="Title")]
    goal: Annotated[str | None, Field(description="What we're trying to achieve", title="Goal")] = (
        None
    )
    approach: Annotated[
        str | None, Field(description="How we're approaching it", title="Approach")
    ] = None
    success_criteria: Annotated[
        str | None, Field(description="How we know we're done", title="Success Criteria")
    ] = None
    status: Annotated[Status8 | None, Field(description="Current status", title="Status")] = (
        "pending"
    )
    started_at: Annotated[
        AwareDatetime | None, Field(description="When stage started", title="Started At")
    ] = None
    completed_at: Annotated[
        AwareDatetime | None, Field(description="When stage completed", title="Completed At")
    ] = None
    current_iteration: Annotated[
        int | None, Field(description="Current iteration", title="Current Iteration")
    ] = None
    max_iterations: Annotated[
        int | None, Field(description="Maximum iterations", title="Max Iterations")
    ] = None
    progress: Annotated[float | None, Field(description="Progress 0.0-1.0", title="Progress")] = (
        None
    )
    total_nodes: Annotated[
        int | None, Field(description="Total nodes in this stage", title="Total Nodes")
    ] = 0
    buggy_nodes: Annotated[
        int | None, Field(description="Number of buggy nodes", title="Buggy Nodes")
    ] = 0
    good_nodes: Annotated[
        int | None, Field(description="Number of good nodes", title="Good Nodes")
    ] = 0


class StageProgressEvent(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    iteration: Annotated[int, Field(title="Iteration")]
    max_iterations: Annotated[int, Field(title="Max Iterations")]
    progress: Annotated[float, Field(title="Progress")]
    total_nodes: Annotated[int, Field(title="Total Nodes")]
    buggy_nodes: Annotated[int, Field(title="Buggy Nodes")]
    good_nodes: Annotated[int, Field(title="Good Nodes")]
    best_metric: Annotated[str | None, Field(title="Best Metric")] = None
    eta_s: Annotated[int | None, Field(title="Eta S")] = None
    latest_iteration_time_s: Annotated[int | None, Field(title="Latest Iteration Time S")] = None


class StageProgressPayload(BaseModel):
    event: StageProgressEvent


class StageSkipWindowEventModel(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    state: Annotated[State, Field(title="State")]
    timestamp: Annotated[str, Field(title="Timestamp")]
    reason: Annotated[str | None, Field(title="Reason")] = None


class StageSkipWindowPayload(BaseModel):
    event: StageSkipWindowEventModel


class StageStartedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["stage_started"], Field(title="Type")] = "stage_started"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    stage_name: Annotated[str, Field(description="Human-readable stage name", title="Stage Name")]
    goal: Annotated[str | None, Field(description="What we're trying to achieve", title="Goal")] = (
        None
    )


class SubstageCompletedEvent(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    main_stage_number: Annotated[int, Field(title="Main Stage Number")]
    reason: Annotated[str, Field(title="Reason")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class SubstageCompletedPayload(BaseModel):
    event: SubstageCompletedEvent


class SubstageSummaryEvent(BaseModel):
    stage: Annotated[str, Field(title="Stage")]
    summary: Annotated[dict[str, Any], Field(title="Summary")]


class SubstageSummaryPayload(BaseModel):
    event: SubstageSummaryEvent


class SummaryResponse(BaseModel):
    summary: Annotated[str, Field(description="Generated or updated summary", title="Summary")]


class TerminateExecutionRequest(BaseModel):
    payload: Annotated[str, Field(title="Payload")]


class TerminateExecutionResponse(BaseModel):
    execution_id: Annotated[str, Field(title="Execution Id")]
    status: Annotated[Literal["terminating"], Field(title="Status")]


class TokenUsageEvent(BaseModel):
    provider: Annotated[str, Field(title="Provider")]
    model: Annotated[str, Field(title="Model")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    cached_input_tokens: Annotated[int, Field(title="Cached Input Tokens")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]


class TokenUsagePayload(BaseModel):
    event: TokenUsageEvent


class TreeVizItem(BaseModel):
    id: Annotated[int, Field(description="Tree viz identifier", title="Id")]
    run_id: Annotated[str, Field(description="Research run identifier", title="Run Id")]
    stage_id: Annotated[
        str, Field(description="Stage identifier (stage_1..stage_4)", title="Stage Id")
    ]
    version: Annotated[
        int, Field(description="Version counter for the stored viz", title="Version")
    ]
    viz: Annotated[dict[str, Any], Field(description="Tree visualization payload", title="Viz")]
    created_at: Annotated[
        str, Field(description="ISO timestamp when the viz was stored", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO timestamp when the viz was last updated", title="Updated At")
    ]


class TreeVizStoredEvent(BaseModel):
    stage_id: Annotated[str, Field(title="Stage Id")]
    version: Annotated[int, Field(title="Version")]
    viz: Annotated[dict[str, Any], Field(title="Viz")]


class TreeVizStoredPayload(BaseModel):
    event: TreeVizStoredEvent


class UserListItem(BaseModel):
    id: Annotated[int, Field(description="Database user ID", title="Id")]
    email: Annotated[str, Field(description="User email address", title="Email")]
    name: Annotated[str, Field(description="User display name", title="Name")]


class UserListResponse(BaseModel):
    items: Annotated[list[UserListItem], Field(description="List of users", title="Items")]
    total: Annotated[int, Field(description="Total count of users", title="Total")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class WalletCreditsData(BaseModel):
    balance: Annotated[int, Field(title="Balance")]


class WalletCreditsEvent(BaseModel):
    type: Annotated[Literal["credits"], Field(title="Type")]
    data: WalletCreditsData


class WalletHeartbeatEvent(BaseModel):
    type: Annotated[Literal["heartbeat"], Field(title="Type")]
    data: Annotated[dict[str, Any] | None, Field(title="Data")] = None


class WalletStreamEvent(RootModel[WalletCreditsEvent | WalletHeartbeatEvent]):
    root: Annotated[
        WalletCreditsEvent | WalletHeartbeatEvent,
        Field(
            description="Root model for wallet SSE updates.",
            discriminator="type",
            title="WalletStreamEvent",
        ),
    ]


class AuthStatus(BaseModel):
    authenticated: Annotated[
        bool, Field(description="Whether the user is authenticated", title="Authenticated")
    ]
    user: Annotated[AuthUser | None, Field(description="User information if authenticated")] = None


class BillingWalletResponse(BaseModel):
    balance: Annotated[int, Field(title="Balance")]
    transactions: Annotated[list[CreditTransactionModel], Field(title="Transactions")]


class ChatMessage(BaseModel):
    role: Annotated[str, Field(description="Message role ('user' or 'assistant')", title="Role")]
    content: Annotated[str, Field(description="Message content", title="Content")]
    sequence_number: Annotated[
        int, Field(description="Sequence number for ordering", title="Sequence Number")
    ]
    created_at: Annotated[
        str, Field(description="ISO format creation timestamp", title="Created At")
    ]
    sent_by_user_id: Annotated[
        int, Field(description="ID of the user who sent this message", title="Sent By User Id")
    ]
    sent_by_user_name: Annotated[
        str, Field(description="Name of the user who sent this message", title="Sent By User Name")
    ]
    sent_by_user_email: Annotated[
        str,
        Field(description="Email of the user who sent this message", title="Sent By User Email"),
    ]
    attachments: Annotated[
        list[FileAttachment] | None,
        Field(description="File attachments for this message", title="Attachments"),
    ] = None


class ChatStreamEvent(
    RootModel[
        ChatStreamStatusEvent
        | ChatStreamContentEvent
        | ChatStreamIdeaUpdatedEvent
        | ChatStreamErrorEvent
        | ChatStreamDoneEvent
    ]
):
    root: Annotated[
        ChatStreamStatusEvent
        | ChatStreamContentEvent
        | ChatStreamIdeaUpdatedEvent
        | ChatStreamErrorEvent
        | ChatStreamDoneEvent,
        Field(
            description="Root model exposed in OpenAPI for chat SSE events.",
            discriminator="type",
            title="ChatStreamEvent",
        ),
    ]


class ConversationCostResponse(BaseModel):
    total_cost: Annotated[float, Field(title="Total Cost")]
    cost_by_model: Annotated[list[ModelCost], Field(title="Cost By Model")]
    cost_by_research: Annotated[list[ResearchCost], Field(title="Cost By Research")]


class ConversationImportConflictData(BaseModel):
    conversations: Annotated[list[ConversationImportConflictItem], Field(title="Conversations")]


class ConversationImportConflictEvent(BaseModel):
    type: Annotated[Literal["conflict"], Field(title="Type")]
    data: ConversationImportConflictData


class ConversationImportProgressEvent(BaseModel):
    type: Annotated[Literal["progress"], Field(title="Type")]
    data: ConversationImportProgressPayload


class ConversationResponse(BaseModel):
    id: Annotated[int, Field(description="Database ID of the conversation", title="Id")]
    url: Annotated[str, Field(description="Original conversation share URL", title="Url")]
    title: Annotated[str, Field(description="Conversation title", title="Title")]
    import_date: Annotated[
        str, Field(description="ISO format import timestamp", title="Import Date")
    ]
    created_at: Annotated[
        str, Field(description="ISO format creation timestamp", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO format last update timestamp", title="Updated At")
    ]
    has_images: Annotated[
        bool | None, Field(description="Whether conversation contains images", title="Has Images")
    ] = None
    has_pdfs: Annotated[
        bool | None, Field(description="Whether conversation contains PDFs", title="Has Pdfs")
    ] = None
    user_id: Annotated[
        int, Field(description="ID of the user who imported the conversation", title="User Id")
    ]
    user_name: Annotated[
        str, Field(description="Name of the user who imported the conversation", title="User Name")
    ]
    user_email: Annotated[
        str,
        Field(description="Email of the user who imported the conversation", title="User Email"),
    ]
    status: Annotated[
        str,
        Field(
            description="Conversation status: 'draft' (initial) or 'with_research' (has research runs)",
            title="Status",
        ),
    ]
    imported_chat: Annotated[
        list[ImportedChatMessage] | None,
        Field(description="Conversation messages (optional)", title="Imported Chat"),
    ] = None
    manual_title: Annotated[
        str | None,
        Field(
            description="Manual title provided when the conversation originates from a manual seed",
            title="Manual Title",
        ),
    ] = None
    manual_hypothesis: Annotated[
        str | None,
        Field(
            description="Manual hypothesis provided when the conversation originates from a manual seed",
            title="Manual Hypothesis",
        ),
    ] = None
    research_runs: Annotated[
        list[ResearchRunSummary] | None,
        Field(
            description="Research pipeline runs associated with the conversation",
            title="Research Runs",
        ),
    ] = None
    parent_run_id: Annotated[
        str | None,
        Field(
            description="Run ID of the parent research run if this conversation was seeded from a run",
            title="Parent Run Id",
        ),
    ] = None


class ConversationUpdateResponse(BaseModel):
    conversation: Annotated[ConversationResponse, Field(description="Updated conversation")]


class CreditPackListResponse(BaseModel):
    packs: Annotated[list[CreditPackModel], Field(title="Packs")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class Idea(BaseModel):
    idea_id: Annotated[int, Field(description="Idea ID", title="Idea Id")]
    conversation_id: Annotated[
        int, Field(description="Associated conversation ID", title="Conversation Id")
    ]
    active_version: Annotated[IdeaVersion | None, Field(description="Currently active version")] = (
        None
    )
    created_at: Annotated[
        str, Field(description="ISO format creation timestamp", title="Created At")
    ]
    updated_at: Annotated[
        str, Field(description="ISO format last update timestamp", title="Updated At")
    ]


class IdeaGetResponse(BaseModel):
    idea: Annotated[Idea, Field(description="Retrieved idea")]


class IdeaUpdateResponse(BaseModel):
    idea: Annotated[Idea, Field(description="Updated idea")]


class MetricCollection(BaseModel):
    primary: Annotated[MetricInterpretation, Field(description="Primary metric being optimized")]
    secondary: Annotated[
        list[MetricInterpretation] | None,
        Field(description="Additional metrics tracked", title="Secondary"),
    ] = None


class NodeResultEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["node_result"], Field(title="Type")] = "node_result"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    outcome: Annotated[Outcome, Field(description="Execution outcome", title="Outcome")]
    summary: Annotated[
        str | None, Field(description="Brief description of what occurred", title="Summary")
    ] = None
    metrics: Annotated[MetricCollection | None, Field(description="Interpreted metrics")] = None
    error_type: Annotated[
        str | None, Field(description="Error type if failed", title="Error Type")
    ] = None
    error_summary: Annotated[
        str | None, Field(description="Error explanation if failed", title="Error Summary")
    ] = None
    exec_time: Annotated[
        float | None, Field(description="Execution time in seconds", title="Exec Time")
    ] = None


class ProgressUpdateEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["progress_update"], Field(title="Type")] = "progress_update"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    current_focus: Annotated[
        str | None, Field(description="What's happening right now", title="Current Focus")
    ] = None
    iteration: Annotated[
        int,
        Field(description="Current iteration within the stage (1-based index)", title="Iteration"),
    ]
    max_iterations: Annotated[
        int, Field(description="Total iterations planned", title="Max Iterations")
    ]
    current_best: Annotated[
        MetricCollection | None, Field(description="Current best metrics if available")
    ] = None


class ResearchRunArtifactEvent(BaseModel):
    type: Annotated[Literal["artifact"], Field(title="Type")]
    data: ResearchRunArtifactMetadata


class ResearchRunBestNodeEvent(BaseModel):
    type: Annotated[Literal["best_node_selection"], Field(title="Type")]
    data: ResearchRunBestNodeSelection


class ResearchRunCodeExecution(BaseModel):
    execution_id: Annotated[
        str,
        Field(description="Unique identifier for the code execution attempt", title="Execution Id"),
    ]
    stage_name: Annotated[
        str, Field(description="Stage name reported by the research pipeline", title="Stage Name")
    ]
    run_type: Annotated[
        RunType,
        Field(
            description="Type of execution ('codex_execution' for the Codex session, 'runfile_execution' for the runfile command)."
        ),
    ]
    code: Annotated[
        str | None, Field(description="Python source code submitted for execution", title="Code")
    ] = None
    status: Annotated[
        str, Field(description="Execution status reported by the worker", title="Status")
    ]
    started_at: Annotated[
        str, Field(description="ISO timestamp when execution began", title="Started At")
    ]
    completed_at: Annotated[
        str | None, Field(description="ISO timestamp when execution ended", title="Completed At")
    ] = None
    exec_time: Annotated[
        float | None, Field(description="Execution time reported by the worker", title="Exec Time")
    ] = None


class ResearchRunCodeExecutionCompletedData(BaseModel):
    execution_id: Annotated[str, Field(title="Execution Id")]
    stage_name: Annotated[str, Field(title="Stage Name")]
    run_type: RunType
    status: Annotated[Status1, Field(title="Status")]
    exec_time: Annotated[float, Field(title="Exec Time")]
    completed_at: Annotated[str, Field(title="Completed At")]


class ResearchRunCodeExecutionCompletedEvent(BaseModel):
    type: Annotated[Literal["code_execution_completed"], Field(title="Type")]
    data: ResearchRunCodeExecutionCompletedData


class ResearchRunCodeExecutionStartedData(BaseModel):
    execution_id: Annotated[str, Field(title="Execution Id")]
    stage_name: Annotated[str, Field(title="Stage Name")]
    run_type: RunType
    code: Annotated[str, Field(title="Code")]
    started_at: Annotated[str, Field(title="Started At")]


class ResearchRunCodeExecutionStartedEvent(BaseModel):
    type: Annotated[Literal["code_execution_started"], Field(title="Type")]
    data: ResearchRunCodeExecutionStartedData


class ResearchRunDetailsResponse(BaseModel):
    run: Annotated[ResearchRunInfo, Field(description="Metadata describing the run")]
    stage_progress: Annotated[
        list[ResearchRunStageProgress] | None,
        Field(description="Stage progress telemetry", title="Stage Progress"),
    ] = None
    logs: Annotated[
        list[ResearchRunLogEntry] | None,
        Field(description="Log events generated by the run", title="Logs"),
    ] = None
    substage_events: Annotated[
        list[ResearchRunSubstageEvent] | None,
        Field(description="Sub-stage completion events", title="Substage Events"),
    ] = None
    substage_summaries: Annotated[
        list[ResearchRunSubstageSummary] | None,
        Field(
            description="LLM-generated summaries for completed sub-stages",
            title="Substage Summaries",
        ),
    ] = None
    best_node_selections: Annotated[
        list[ResearchRunBestNodeSelection] | None,
        Field(
            description="Reasoning records captured whenever a best node is selected",
            title="Best Node Selections",
        ),
    ] = None
    events: Annotated[
        list[ResearchRunEvent] | None,
        Field(
            description="Audit events describing run-level lifecycle transitions", title="Events"
        ),
    ] = None
    artifacts: Annotated[
        list[ResearchRunArtifactMetadata] | None,
        Field(description="Artifacts uploaded for the run", title="Artifacts"),
    ] = None
    tree_viz: Annotated[
        list[TreeVizItem] | None,
        Field(description="Tree visualizations stored for this run", title="Tree Viz"),
    ] = None
    paper_generation_progress: Annotated[
        list[ResearchRunPaperGenerationProgress] | None,
        Field(
            description="Paper generation progress events (Stage 5)",
            title="Paper Generation Progress",
        ),
    ] = None
    stage_skip_windows: Annotated[
        list[ResearchRunStageSkipWindow] | None,
        Field(
            description="Windows indicating when each stage became skippable.",
            title="Stage Skip Windows",
        ),
    ] = None
    child_conversations: Annotated[
        list[ChildConversationInfo] | None,
        Field(
            description="Conversations that were seeded from this run", title="Child Conversations"
        ),
    ] = None


class ResearchRunInitialEventData(BaseModel):
    run: ResearchRunInfo
    stage_progress: Annotated[list[ResearchRunStageProgress], Field(title="Stage Progress")]
    logs: Annotated[list[ResearchRunLogEntry], Field(title="Logs")]
    substage_events: Annotated[list[ResearchRunSubstageEvent], Field(title="Substage Events")]
    substage_summaries: Annotated[
        list[ResearchRunSubstageSummary], Field(title="Substage Summaries")
    ]
    artifacts: Annotated[list[ResearchRunArtifactMetadata], Field(title="Artifacts")]
    tree_viz: Annotated[list[TreeVizItem], Field(title="Tree Viz")]
    events: Annotated[list[ResearchRunEvent], Field(title="Events")]
    paper_generation_progress: Annotated[
        list[ResearchRunPaperGenerationProgress], Field(title="Paper Generation Progress")
    ]
    best_node_selections: Annotated[
        list[ResearchRunBestNodeSelection], Field(title="Best Node Selections")
    ]
    stage_skip_windows: Annotated[
        list[ResearchRunStageSkipWindow] | None,
        Field(
            description="Recorded windows when stages became skippable.", title="Stage Skip Windows"
        ),
    ] = None
    hw_cost_estimate: Annotated[
        ResearchRunHwCostEstimateData | None,
        Field(
            description="Hardware cost estimate available when the initial snapshot was emitted."
        ),
    ] = None
    hw_cost_actual: Annotated[
        ResearchRunHwCostActualData | None,
        Field(description="Hardware cost billed so far, if available."),
    ] = None
    code_executions: Annotated[
        dict[str, ResearchRunCodeExecution] | None,
        Field(
            description="Latest code execution snapshot per run_type for the run.",
            title="Code Executions",
        ),
    ] = None
    child_conversations: Annotated[
        list[ChildConversationInfo] | None,
        Field(
            description="Conversations that were seeded from this run.", title="Child Conversations"
        ),
    ] = None


class ResearchRunPaperGenerationEvent(BaseModel):
    type: Annotated[Literal["paper_generation_progress"], Field(title="Type")]
    data: ResearchRunPaperGenerationProgress


class ResearchRunStageSkipWindowEvent(BaseModel):
    type: Annotated[Literal["stage_skip_window"], Field(title="Type")]
    data: ResearchRunStageSkipWindowUpdate


class ResearchRunSubstageCompletedEvent(BaseModel):
    type: Annotated[Literal["substage_completed"], Field(title="Type")]
    data: ResearchRunSubstageEvent


class RunCompletedEventPayload(BaseModel):
    execution_id: Annotated[str, Field(title="Execution Id")]
    stage_name: Annotated[str, Field(title="Stage Name")]
    status: Annotated[Status6, Field(title="Status")]
    exec_time: Annotated[float, Field(title="Exec Time")]
    completed_at: Annotated[str, Field(title="Completed At")]
    run_type: RunType


class RunCompletedPayload(BaseModel):
    event: RunCompletedEventPayload


class RunFinishedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["run_finished"], Field(title="Type")] = "run_finished"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    status: Annotated[Status7, Field(description="Final run status", title="Status")]
    success: Annotated[
        bool, Field(description="Whether the run completed successfully", title="Success")
    ]
    reason: Annotated[Reason, Field(description="Why the run finished", title="Reason")]
    message: Annotated[
        str | None, Field(description="Human-readable completion message", title="Message")
    ] = None
    summary: Annotated[
        str | None, Field(description="Summary of what was accomplished", title="Summary")
    ] = None
    total_duration_seconds: Annotated[
        float | None,
        Field(description="Total run duration in seconds", title="Total Duration Seconds"),
    ] = None
    stages_completed: Annotated[
        int | None, Field(description="Number of stages completed", title="Stages Completed")
    ] = 0
    total_nodes_executed: Annotated[
        int | None, Field(description="Total nodes executed", title="Total Nodes Executed")
    ] = 0
    best_result: Annotated[
        MetricCollection | None, Field(description="Best result achieved if available")
    ] = None


class StageCompletedEvent(BaseModel):
    id: Annotated[str, Field(description="Unique event ID (UUID)", title="Id")]
    timestamp: Annotated[
        AwareDatetime, Field(description="When this event occurred", title="Timestamp")
    ]
    stage: Annotated[
        str, Field(description="Stage identifier (e.g., '1_initial_implementation')", title="Stage")
    ]
    node_id: Annotated[
        str | None, Field(description="Node ID if event relates to specific node", title="Node Id")
    ] = None
    type: Annotated[Literal["stage_completed"], Field(title="Type")] = "stage_completed"
    headline: Annotated[str, Field(description="Short headline", title="Headline")]
    summary: Annotated[
        str | None,
        Field(description="What was accomplished (from substage_summary)", title="Summary"),
    ] = None
    best_node_id: Annotated[
        str | None, Field(description="ID of best node from this stage", title="Best Node Id")
    ] = None
    best_metrics: Annotated[MetricCollection | None, Field(description="Best metrics achieved")] = (
        None
    )
    total_attempts: Annotated[
        int | None, Field(description="Total nodes explored", title="Total Attempts")
    ] = 0
    successful_attempts: Annotated[
        int | None,
        Field(description="Nodes that completed successfully", title="Successful Attempts"),
    ] = 0
    failed_attempts: Annotated[
        int | None, Field(description="Nodes that failed", title="Failed Attempts")
    ] = 0
    confidence: Annotated[
        Confidence | None,
        Field(description="Confidence in results (from substage_summary)", title="Confidence"),
    ] = None


class ChatHistoryResponse(BaseModel):
    chat_messages: Annotated[
        list[ChatMessage], Field(description="List of chat messages", title="Chat Messages")
    ]


class ConversationImportDoneData(BaseModel):
    conversation: ConversationResponse | None = None
    idea: Idea | None = None
    error: Annotated[str | None, Field(title="Error")] = None


class ConversationImportDoneEvent(BaseModel):
    type: Annotated[Literal["done"], Field(title="Type")]
    data: ConversationImportDoneData


class ConversationImportStreamEvent(
    RootModel[
        ConversationImportSectionUpdateEvent
        | ConversationImportStateEvent
        | ConversationImportProgressEvent
        | ConversationImportConflictEvent
        | ConversationImportModelLimitEvent
        | ConversationImportErrorEvent
        | ConversationImportDoneEvent
        | ConversationImportContentEvent
        | ConversationImportMarkdownDeltaEvent
    ]
):
    root: Annotated[
        ConversationImportSectionUpdateEvent
        | ConversationImportStateEvent
        | ConversationImportProgressEvent
        | ConversationImportConflictEvent
        | ConversationImportModelLimitEvent
        | ConversationImportErrorEvent
        | ConversationImportDoneEvent
        | ConversationImportContentEvent
        | ConversationImportMarkdownDeltaEvent,
        Field(
            description="Root model for conversation import SSE stream events.",
            discriminator="type",
            title="ConversationImportStreamEvent",
        ),
    ]


class ResearchRunInitialEvent(BaseModel):
    type: Annotated[Literal["initial"], Field(title="Type")]
    data: ResearchRunInitialEventData


class ResearchRunState(BaseModel):
    run_id: Annotated[str, Field(description="Unique run identifier", title="Run Id")]
    status: Annotated[Status3, Field(title="Status")]
    conversation_id: Annotated[int, Field(title="Conversation Id")]
    idea_title: Annotated[str | None, Field(title="Idea Title")] = None
    idea_markdown: Annotated[str | None, Field(title="Idea Markdown")] = None
    stages: Annotated[list[StageGoal] | None, Field(title="Stages")] = None
    current_stage: Annotated[str | None, Field(title="Current Stage")] = None
    current_stage_goal: StageGoal | None = None
    timeline: Annotated[
        list[
            Annotated[
                RunStartedEvent
                | StageStartedEvent
                | NodeResultEvent
                | StageCompletedEvent
                | ProgressUpdateEvent
                | PaperGenerationStepEvent
                | NodeExecutionStartedEvent
                | NodeExecutionCompletedEvent
                | RunFinishedEvent,
                Field(discriminator="type"),
            ]
        ]
        | None,
        Field(title="Timeline"),
    ] = None
    current_focus: Annotated[str | None, Field(title="Current Focus")] = None
    active_nodes: Annotated[list[ActiveNode] | None, Field(title="Active Nodes")] = None
    overall_progress: Annotated[float | None, Field(title="Overall Progress")] = 0.0
    current_stage_progress: Annotated[float | None, Field(title="Current Stage Progress")] = 0.0
    best_node_id: Annotated[str | None, Field(title="Best Node Id")] = None
    best_metrics: MetricCollection | None = None
    best_node_reasoning: Annotated[str | None, Field(title="Best Node Reasoning")] = None
    artifact_ids: Annotated[list[int] | None, Field(title="Artifact Ids")] = None
    tree_viz: Annotated[dict[str, Any] | None, Field(title="Tree Viz")] = None
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    started_running_at: Annotated[AwareDatetime | None, Field(title="Started Running At")] = None
    completed_at: Annotated[AwareDatetime | None, Field(title="Completed At")] = None
    gpu_type: Annotated[str | None, Field(title="Gpu Type")] = None
    estimated_cost_cents: Annotated[int | None, Field(title="Estimated Cost Cents")] = None
    actual_cost_cents: Annotated[int | None, Field(title="Actual Cost Cents")] = None
    cost_per_hour_cents: Annotated[int | None, Field(title="Cost Per Hour Cents")] = None
    error_message: Annotated[str | None, Field(title="Error Message")] = None
    version: Annotated[int | None, Field(title="Version")] = 1


class ResearchRunStreamEvent(
    RootModel[
        ResearchRunInitialEvent
        | ResearchRunCompleteEvent
        | ResearchRunStageProgressEvent
        | ResearchRunRunEvent
        | ResearchRunInitializationStatusEvent
        | ResearchRunTerminationStatusEvent
        | ResearchRunLogEvent
        | ResearchRunArtifactEvent
        | ResearchRunReviewCompletedEvent
        | ResearchRunBestNodeEvent
        | ResearchRunSubstageCompletedEvent
        | ResearchRunPaperGenerationEvent
        | ResearchRunSubstageEventStream
        | ResearchRunSubstageSummaryEvent
        | ResearchRunCodeExecutionStartedEvent
        | ResearchRunCodeExecutionCompletedEvent
        | ResearchRunStageSkipWindowEvent
        | ResearchRunHeartbeatEvent
        | ResearchRunHwCostEstimateEvent
        | ResearchRunHwCostActualEvent
        | ResearchRunErrorEvent
    ]
):
    root: Annotated[
        ResearchRunInitialEvent
        | ResearchRunCompleteEvent
        | ResearchRunStageProgressEvent
        | ResearchRunRunEvent
        | ResearchRunInitializationStatusEvent
        | ResearchRunTerminationStatusEvent
        | ResearchRunLogEvent
        | ResearchRunArtifactEvent
        | ResearchRunReviewCompletedEvent
        | ResearchRunBestNodeEvent
        | ResearchRunSubstageCompletedEvent
        | ResearchRunPaperGenerationEvent
        | ResearchRunSubstageEventStream
        | ResearchRunSubstageSummaryEvent
        | ResearchRunCodeExecutionStartedEvent
        | ResearchRunCodeExecutionCompletedEvent
        | ResearchRunStageSkipWindowEvent
        | ResearchRunHeartbeatEvent
        | ResearchRunHwCostEstimateEvent
        | ResearchRunHwCostActualEvent
        | ResearchRunErrorEvent,
        Field(
            description="Root model for research pipeline SSE events.",
            discriminator="type",
            title="ResearchRunStreamEvent",
        ),
    ]
