"""Research pipeline API endpoints: events, file uploads, and authentication."""

from fastapi import APIRouter

from .auth import ResearchRunStore, resolve_run_owner_first_name, verify_run_auth
from .file_uploads import router as file_uploads_router
from .research_pipeline_webhooks import (
    BYTES_PER_GB,
    LOW_FREE_DISK_THRESHOLD_BYTES,
    record_disk_usage_event,
    resolve_partition_capacity_bytes,
)
from .research_pipeline_webhooks import router as webhooks_router
from .schemas import (
    ArtifactUploadedEvent,
    ArtifactUploadedPayload,
    CodexEventPayload,
    DatasetFileInfo,
    DatasetUploadUrlRequest,
    DatasetUploadUrlResponse,
    DiskUsagePartition,
    FigureReviewEvent,
    FigureReviewsEvent,
    FigureReviewsPayload,
    GPUShortagePayload,
    HardwareStatsPartition,
    HardwareStatsPayload,
    HeartbeatPayload,
    InitializationProgressPayload,
    ListDatasetsRequest,
    ListDatasetsResponse,
    MultipartUploadAbortRequest,
    MultipartUploadCompleteRequest,
    MultipartUploadCompleteResponse,
    MultipartUploadInitRequest,
    MultipartUploadInitResponse,
    MultipartUploadPart,
    MultipartUploadPartUrl,
    PaperGenerationProgressEvent,
    PaperGenerationProgressPayload,
    ParentRunFileInfo,
    ParentRunFilesRequest,
    ParentRunFilesResponse,
    PresignedUploadUrlRequest,
    PresignedUploadUrlResponse,
    ReviewCompletedEvent,
    ReviewCompletedPayload,
    RunCompletedEventPayload,
    RunCompletedPayload,
    RunFinishedPayload,
    RunLogEvent,
    RunLogPayload,
    RunningCodeEventPayload,
    RunningCodePayload,
    RunStartedPayload,
    StageProgressEvent,
    StageProgressPayload,
    StageSkipWindowEventModel,
    StageSkipWindowPayload,
    SubstageCompletedEvent,
    SubstageCompletedPayload,
    SubstageSummaryEvent,
    SubstageSummaryPayload,
    TokenUsageEvent,
    TokenUsagePayload,
    TreeVizStoredEvent,
    TreeVizStoredPayload,
)

# Create a combined router with the same prefix/tags as the original
router = APIRouter(prefix="/research-pipeline/events", tags=["research-pipeline-events"])

# Include sub-routers (they don't have their own prefix)
router.include_router(webhooks_router)
router.include_router(file_uploads_router)

__all__ = [
    # Router
    "router",
    # Auth
    "ResearchRunStore",
    "resolve_run_owner_first_name",
    "verify_run_auth",
    # Disk usage
    "BYTES_PER_GB",
    "LOW_FREE_DISK_THRESHOLD_BYTES",
    "record_disk_usage_event",
    "resolve_partition_capacity_bytes",
    # Schemas - Event payloads
    "ArtifactUploadedEvent",
    "ArtifactUploadedPayload",
    "CodexEventPayload",
    "DiskUsagePartition",
    "FigureReviewEvent",
    "FigureReviewsEvent",
    "FigureReviewsPayload",
    "GPUShortagePayload",
    "HardwareStatsPartition",
    "HardwareStatsPayload",
    "HeartbeatPayload",
    "InitializationProgressPayload",
    "PaperGenerationProgressEvent",
    "PaperGenerationProgressPayload",
    "ReviewCompletedEvent",
    "ReviewCompletedPayload",
    "RunCompletedEventPayload",
    "RunCompletedPayload",
    "RunFinishedPayload",
    "RunLogEvent",
    "RunLogPayload",
    "RunningCodeEventPayload",
    "RunningCodePayload",
    "RunStartedPayload",
    "StageProgressEvent",
    "StageProgressPayload",
    "StageSkipWindowEventModel",
    "StageSkipWindowPayload",
    "SubstageCompletedEvent",
    "SubstageCompletedPayload",
    "SubstageSummaryEvent",
    "SubstageSummaryPayload",
    "TokenUsageEvent",
    "TokenUsagePayload",
    "TreeVizStoredEvent",
    "TreeVizStoredPayload",
    # Schemas - File upload
    "DatasetFileInfo",
    "DatasetUploadUrlRequest",
    "DatasetUploadUrlResponse",
    "ListDatasetsRequest",
    "ListDatasetsResponse",
    "MultipartUploadAbortRequest",
    "MultipartUploadCompleteRequest",
    "MultipartUploadCompleteResponse",
    "MultipartUploadInitRequest",
    "MultipartUploadInitResponse",
    "MultipartUploadPart",
    "MultipartUploadPartUrl",
    "ParentRunFileInfo",
    "ParentRunFilesRequest",
    "ParentRunFilesResponse",
    "PresignedUploadUrlRequest",
    "PresignedUploadUrlResponse",
]
